# Generated by Django 5.1.4 on 2025-01-02 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('name', models.CharField(max_length=50)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='document.client')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='document.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^(VTE|EC)\\d+$')])),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.category')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=10)),
                ('doc_type', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('sequence_number', models.IntegerField()),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.client')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.entity')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=10)),
                ('doc_type', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('sequence_number', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.client')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.entity')),
                ('offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma', to='document.offre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='proforma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formation', to='document.proforma'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=10)),
                ('doc_type', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('sequence_number', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.client')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.entity')),
                ('proforma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='document.proforma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttestationFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=10)),
                ('doc_type', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('sequence_number', models.IntegerField()),
                ('details_formation', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.client')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.entity')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='document.formation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='document.participant')),
                ('proforma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='document.proforma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='BROUILLON', max_length=10)),
                ('doc_type', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('sequence_number', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.client')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.entity')),
                ('proforma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='document.proforma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.client')),
            ],
        ),
        migrations.AddField(
            model_name='offre',
            name='sites',
            field=models.ManyToManyField(to='document.site'),
        ),
    ]
