# Generated by Django 5.1.4 on 2025-01-06 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('sequence_number', models.IntegerField()),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin_prevue', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.client')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.entity')),
                ('offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affaire', to='document.offre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
