# Generated by Django 5.1.4 on 2025-01-08 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_attestationformation_proforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='document.affaire'),
        ),
    ]
