# Generated by Django 5.1.4 on 2025-01-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_rapport_affaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='proforma',
        ),
        migrations.AddField(
            model_name='formation',
            name='affaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='document.affaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='rapport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formation', to='document.rapport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='produit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='document.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
