# Generated by Django 5.1.4 on 2025-01-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_remove_formation_proforma_formation_affaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoris', to='document.entity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='document.category'),
        ),
    ]
